name: flutter_paystack
description: A Flutter plugin for making payments via Paystack Payment Gateway. Completely supports Android and iOS.
version: 1.0.7
homepage: https://github.com/wilburt/flutter_paystack

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: any
  meta: ^1.9.1
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: any
  mockito: ^5.4.2


flutter:
  plugin:
    platforms:
      android:
        package: co.paystack.flutterpaystack
        pluginClass:  FlutterPaystackPlugin
      ios:
        pluginClass:  FlutterPaystackPlugin

  assets:
   - assets/images/



environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=3.10.0"
